# Header
menu:
  军的小屋: /
  归档: /archives
  书签: /favorites
  开源仓库: /openCode
  关于: /about

menu_icons:
  enable: true

# Content
excerpt_link: Read More
fancybox: false

social:
  GitHub: https://github.com/Longjunzhi || github
  Weibo: https://weibo.com/u/1349974130 || weibo

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:

baidu_site_verification: true
baidu_site_verification_content: 'codeva-cSR3vf2y9M'
sogou_site_verification: true
sogou_site_verification_content: 'Bu8E4GUknz'
author: 庞学军